---
title: "Project 3 Skills Job Posts"
authors: ""
date: "3/21/2020"
output: html_document
---


```{r}
if (!require('XML')) install.packages('XML')
library(XML)
```


```{r}
# Reading XML file from the web
con <-'https://stackoverflow.com/jobs/feed?dr=DataScientist&j=permanent%2ccontract'
job_raw<-readLines(con, warn = FALSE)

#function that scraps node category which contains job skills
require(XML)
Fun1 <- function(xdata){
  dum <- xmlParse(xdata)
  xDf<- xmlToDataFrame(nodes = getNodeSet(dum, "//*/category"), stringsAsFactors = FALSE)
  xDf
}

# calling function and converting data frame
skills<-Fun1(job_raw)
skills_tbl<-sort(table(skills), decreasing=T)
skills_tbl<-data.frame(skills_tbl)

# writing table to database for comparison
# writing function is commented out as table has already been created, results are showed

# <ourgroupname> is no capitals and no spaces
host="soundsgood.crg53husyk2z.us-east-2.rds.amazonaws.com"
port="5432"
database="soundsgood"
username="soundsgood"
password="soundsgood"
drv <- dbDriver("PostgreSQL")
conc <- DBI::dbConnect(drv, 
  host = host,
  user = username,
  password = password)

# write function is commented out
#######    dbWriteTable(conc,"skills_xml",skills_tbl)

# results
(skills_db <- tbl(conc, "skills_xml"))

# converting to a data frame
skills_db<-data.frame(skills_db)

# summarizing 20 most frequent skills
skills_db<-head(skills_db,20)

#Bar Plot
barplot(skills_db$Freq, main=" 20 Most Frequent Skills Required",
   xlab="Skills", names.arg=skills_db$skills, las=2)

dbDisconnect(conc)


```
